# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['run.py'],
    pathex=['/Users/huangwei/素材/Image-Detection-Bypass-Utility-idbuv14r1'],
    binaries=[],
    datas=[],
    hiddenimports=[
        'ui_utils',
        'ui_utils.main_window',
        'ui_utils.worker',
        'ui_utils.analysis_panel',
        'ui_utils.collapsible_box',
        'ui_utils.theme',
        'image_postprocess',
        'image_postprocess.processor',
        'image_postprocess.camera_pipeline',
        'image_postprocess.video_processor',
        'image_postprocess.utils',
        'image_postprocess.utils.autowb',
        'image_postprocess.utils.clahe',
        'image_postprocess.utils.color_lut',
        'image_postprocess.utils.exif',
        'image_postprocess.utils.fourier_pipeline',
        'image_postprocess.utils.fourier_pipeline_new_algo',
        'image_postprocess.utils.fourier_pipeline_v3',
        'image_postprocess.utils.gaussian_noise',
        'image_postprocess.utils.perturbation',
        'image_postprocess.utils.glcm_normalization',
        'image_postprocess.utils.lbp_normalization',
        'image_postprocess.utils.non_semantic_unmarker',
        'image_postprocess.utils.blend',
        'nodes_utils',
        'nodes_utils.cam_opt',
        'nodes_utils.fft_opt',
        'nodes_utils.glcm_opt',
        'nodes_utils.ns_opt',
        'nodes',
        'utils',
        'cv2',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='IDBU',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='IDBU',
)
app = BUNDLE(
    coll,
    name='IDBU.app',
    icon=None,
    bundle_identifier=None,
)
